env:
  BYOND_MAJOR="503"
  BYOND_MINOR="1224"
  PROJNAME="tgstation"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libc6:i386 libgcc1:i386 libstdc++6:i386 -qq

install:
  - curl "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip
  - unzip byond.zip
  - cd byond
  - sudo make install
  - cd ..
  - chmod +x dm.sh

script:
  - ./dm.sh $PROJNAME.dme -DAUTO_TEST -Mautotestmap
  - DreamDaemon $PROJNAME.dmb 2>&1 | tee runtimes.log
  - (! grep -q 'runtime error' runtimes.log)
  - cat test_results.log
  - (! grep -q FAIL test_results.log)
